name: CD

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

env:
  NODE_VERSION: '16'
  PNPM_VERSION: 8

jobs:
  release:
    name: Release Please
    runs-on: ubuntu-latest

    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}

    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release-please
        if: github.event_name != 'workflow_dispatch'
        with:
          token: '${{ secrets.GH_BOT_TOKEN }}'
          command: manifest
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: [release]

    if: github.event_name == 'workflow_dispatch' || needs.release.outputs.releases_created

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get git HEAD sha
        id: commit-vars
        run: |
          echo ::set-output name=git_head_sha::"$(git rev-parse HEAD)"

      - name: Retrieve pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.local/share/pnpm/store
          key: install-${{ env.NODE_VERSION }}-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            install-${{ env.NODE_VERSION }}-${{ runner.os }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      - name: Build
        run: pnpm run build

      - name: Publish to NPM
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Comment on published commit
        uses: peter-evans/commit-comment@v2
        with:
          token: '${{ secrets.GH_BOT_TOKEN }}'
          sha: '${{ steps.commit-vars.outputs.git_head_sha }}'
          body: |
            🤖 This commit was published to NPM!
