name: Renovate Checks

on:
  push:
    branches:
      - 'renovate/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.4.0
      with:
        node-version: '12.x'
        
    - name: Install
      run: npm ci
        
    - name: Lint
      run: npm run lint
        
    - name: Lint Tests
      run: npm run lint-tests
      
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.4.0
      with:
        node-version: '12.x'
        
    - name: Install
      run: npm ci
        
    - name: Build
      run: npm run build
      
    - name: Test
      run: npm run test
      